# Generated by Django 3.1.5 on 2021-01-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
