# Generated by Django 3.1.5 on 2021-01-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lengow_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
